import { describe, expect, it } from 'vitest';
import { applySm2, makeProgress } from './srs';
import { type AnswerQuality } from '../types/api';

/**
 * SM-2 parity: the TS port must produce IDENTICAL schedules to the backend
 * (backend/app/services/srs.py). The expected sequence below was generated by
 * running the Python implementation with the same fixed review timestamp
 * (2026-06-11T12:00:00Z). If either side changes, regenerate this fixture —
 * offline answers and the server replay must agree.
 */
const QUALITY_SEQUENCE: AnswerQuality[] = [3, 3, 3, 5, 5, 0, 3, 3, 5, 0, 5, 3];

const EXPECTED = [
  { repetitions: 1, easiness_factor: 2.5, interval_days: 1, next_review_at: '2026-06-12' },
  { repetitions: 2, easiness_factor: 2.5, interval_days: 6, next_review_at: '2026-06-17' },
  { repetitions: 3, easiness_factor: 2.5, interval_days: 15, next_review_at: '2026-06-26' },
  { repetitions: 4, easiness_factor: 2.65, interval_days: 49, next_review_at: '2026-07-30' },
  { repetitions: 5, easiness_factor: 2.8, interval_days: 169, next_review_at: '2026-11-27' },
  { repetitions: 0, easiness_factor: 2.6, interval_days: 1, next_review_at: '2026-06-12' },
  { repetitions: 1, easiness_factor: 2.6, interval_days: 1, next_review_at: '2026-06-12' },
  { repetitions: 2, easiness_factor: 2.6, interval_days: 6, next_review_at: '2026-06-17' },
  { repetitions: 3, easiness_factor: 2.75, interval_days: 21, next_review_at: '2026-07-02' },
  { repetitions: 0, easiness_factor: 2.55, interval_days: 1, next_review_at: '2026-06-12' },
  { repetitions: 1, easiness_factor: 2.7, interval_days: 1, next_review_at: '2026-06-12' },
  { repetitions: 2, easiness_factor: 2.7, interval_days: 6, next_review_at: '2026-06-17' },
];

describe('applySm2 — parity with backend services/srs.py', () => {
  it('matches the Python-generated schedule step for step', () => {
    const reviewedAt = new Date('2026-06-11T12:00:00Z');
    const progress = makeProgress('q1');

    QUALITY_SEQUENCE.forEach((quality, i) => {
      applySm2(progress, quality, reviewedAt);
      const expected = EXPECTED[i];
      expect(progress.repetitions, `step ${i} repetitions`).toBe(expected.repetitions);
      expect(progress.easiness_factor, `step ${i} EF`).toBeCloseTo(expected.easiness_factor, 10);
      expect(progress.interval_days, `step ${i} interval`).toBe(expected.interval_days);
      expect(progress.next_review_at, `step ${i} next_review`).toBe(expected.next_review_at);
    });
  });

  it('floors the easiness factor at 1.3 after repeated failures', () => {
    const progress = makeProgress('q2');
    for (let i = 0; i < 10; i++) applySm2(progress, 0, new Date('2026-06-11T12:00:00Z'));
    expect(progress.easiness_factor).toBeCloseTo(1.3, 10);
    expect(progress.repetitions).toBe(0);
    expect(progress.interval_days).toBe(1);
  });
});
